export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";

export const GET_TWEET_DATA = "GET_TWEET_DATA";
export const GET_TWEET_DATA_ERROR = "GET_TWEET_DATA_ERROR";
export const GET_TWEET_DATA_RECEIVED = "GET_TWEET_DATA_RECEIVED";
